[build]
  command = "npm run build"
  publish = "dist"  # Make sure this points to the correct directory for your build files.

[dev]
  command = "npm run dev"
  port = 3001  # Local development server port

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "14"  # Specify Node.js version (you can also try 16 if needed)
